require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
end

desc 'Run RSpec specs'
task :spec do
  sh 'bundle exec rspec spec'
end

desc 'Run both the Minitest+Mocha suite and the RSpec suite'
task default: %i[test spec]
